# Global Representativeness Index (GRI) Regional Hierarchies
#
# This file defines geographical hierarchies for aggregating country-level
# data into regional and continental dimensions.

# Country to Region mapping (UN regional classifications)
country_to_region:
  # Eastern Africa
  "Eastern Africa":
    - "Burundi"
    - "Comoros" 
    - "Djibouti"
    - "Eritrea"
    - "Ethiopia"
    - "Kenya"
    - "Madagascar"
    - "Malawi"
    - "Mauritius"
    - "Mayotte"
    - "Mozambique"
    - "Réunion"
    - "Rwanda"
    - "Seychelles"
    - "Somalia"
    - "South Sudan"
    - "Uganda"
    - "Tanzania"
    - "United Republic of Tanzania"
    - "Zambia"
    - "Zimbabwe"
    
  # Middle Africa
  "Middle Africa":
    - "Angola"
    - "Cameroon"
    - "Central African Republic"
    - "Chad"
    - "Congo"
    - "Democratic Republic of the Congo"
    - "Equatorial Guinea"
    - "Gabon"
    - "São Tomé and Príncipe"
    - "Sao Tome and Principe"
    
  # Northern Africa
  "Northern Africa":
    - "Algeria"
    - "Egypt"
    - "Libya"
    - "Morocco"
    - "Sudan"
    - "Tunisia"
    - "Western Sahara"
    
  # Southern Africa
  "Southern Africa":
    - "Botswana"
    - "Eswatini"
    - "Lesotho"
    - "Namibia"
    - "South Africa"
    
  # Western Africa
  "Western Africa":
    - "Benin"
    - "Burkina Faso"
    - "Cabo Verde"
    - "Côte d'Ivoire"
    - "Gambia"
    - "Ghana"
    - "Guinea"
    - "Guinea-Bissau"
    - "Liberia"
    - "Mali"
    - "Mauritania"
    - "Niger"
    - "Nigeria"
    - "Senegal"
    - "Sierra Leone"
    - "Togo"
    
  # Central Asia
  "Central Asia":
    - "Kazakhstan"
    - "Kyrgyzstan"
    - "Tajikistan"
    - "Turkmenistan"
    - "Uzbekistan"
    
  # Eastern Asia
  "Eastern Asia":
    - "China"
    - "China, Hong Kong SAR"
    - "China, Macao SAR"
    - "China, Taiwan Province of China"
    - "Democratic People's Republic of Korea"
    - "Dem. People's Republic of Korea"
    - "Japan"
    - "Mongolia"
    - "Republic of Korea"
    
  # South-eastern Asia
  "South-eastern Asia":
    - "Brunei Darussalam"
    - "Cambodia"
    - "Indonesia"
    - "Lao People's Democratic Republic"
    - "Malaysia"
    - "Myanmar"
    - "Philippines"
    - "Singapore"
    - "Thailand"
    - "Timor-Leste"
    - "Viet Nam"
    - "Vietnam"
    
  # Southern Asia
  "Southern Asia":
    - "Afghanistan"
    - "Bangladesh"
    - "Bhutan"
    - "India"
    - "Iran"
    - "Maldives"
    - "Nepal"
    - "Pakistan"
    - "Sri Lanka"
    
  # Western Asia
  "Western Asia":
    - "Armenia"
    - "Azerbaijan"
    - "Bahrain"
    - "Cyprus"
    - "Georgia"
    - "Iraq"
    - "Israel"
    - "Jordan"
    - "Kuwait"
    - "Lebanon"
    - "Oman"
    - "Qatar"
    - "Saudi Arabia"
    - "State of Palestine"
    - "Syrian Arab Republic"
    - "Turkey"
    - "Türkiye"
    - "United Arab Emirates"
    - "Yemen"
    - "Iran (Islamic Republic of)"
    
  # Eastern Europe
  "Eastern Europe":
    - "Belarus"
    - "Bulgaria"
    - "Czech Republic"
    - "Czechia"
    - "Hungary"
    - "Poland"
    - "Republic of Moldova"
    - "Romania"
    - "Russian Federation"
    - "Slovakia"
    - "Ukraine"
    
  # Northern Europe
  "Northern Europe":
    - "Åland Islands"
    - "Denmark"
    - "Estonia"
    - "Faroe Islands"
    - "Finland"
    - "Guernsey"
    - "Iceland"
    - "Ireland"
    - "Isle of Man"
    - "Jersey"
    - "Latvia"
    - "Lithuania"
    - "Norway"
    - "Sark"
    - "Svalbard and Jan Mayen Islands"
    - "Sweden"
    - "United Kingdom"
    
  # Southern Europe
  "Southern Europe":
    - "Albania"
    - "Andorra"
    - "Bosnia and Herzegovina"
    - "Croatia"
    - "Gibraltar"
    - "Greece"
    - "Holy See"
    - "Italy"
    - "Kosovo (under UNSC res. 1244)"
    - "Malta"
    - "Montenegro"
    - "North Macedonia"
    - "Portugal"
    - "San Marino"
    - "Serbia"
    - "Slovenia"
    - "Spain"
    
  # Western Europe
  "Western Europe":
    - "Austria"
    - "Belgium"
    - "France"
    - "Germany"
    - "Liechtenstein"
    - "Luxembourg"
    - "Monaco"
    - "Netherlands"
    - "Switzerland"
    
  # Caribbean
  "Caribbean":
    - "Anguilla"
    - "Antigua and Barbuda"
    - "Aruba"
    - "Bahamas"
    - "Barbados"
    - "Bonaire, Sint Eustatius and Saba"
    - "British Virgin Islands"
    - "Cayman Islands"
    - "Cuba"
    - "Curaçao"
    - "Dominica"
    - "Dominican Republic"
    - "Grenada"
    - "Guadeloupe"
    - "Haiti"
    - "Jamaica"
    - "Martinique"
    - "Montserrat"
    - "Puerto Rico"
    - "Saint Barthélemy"
    - "Saint Kitts and Nevis"
    - "Saint Lucia"
    - "Saint Martin (French part)"
    - "Saint Vincent and the Grenadines"
    - "Sint Maarten (Dutch part)"
    - "Trinidad and Tobago"
    - "Turks and Caicos Islands"
    - "United States Virgin Islands"
    
  # Central America
  "Central America":
    - "Belize"
    - "Costa Rica"
    - "El Salvador"
    - "Guatemala"
    - "Honduras"
    - "Mexico"
    - "Nicaragua"
    - "Panama"
    
  # Northern America
  "Northern America":
    - "Bermuda"
    - "Canada"
    - "Greenland"
    - "Saint Pierre and Miquelon"
    - "United States"
    - "United States of America"
    
  # South America
  "South America":
    - "Argentina"
    - "Bolivia"
    - "Bolivia (Plurinational State of)"
    - "Bouvet Island"
    - "Brazil"
    - "Chile"
    - "Colombia"
    - "Ecuador"
    - "Falkland Islands (Malvinas)"
    - "French Guiana"
    - "Guyana"
    - "Paraguay"
    - "Peru"
    - "South Georgia and the South Sandwich Islands"
    - "Suriname"
    - "Uruguay"
    - "Venezuela"
    - "Venezuela (Bolivarian Republic of)"
    
  # Australia and New Zealand
  "Australia and New Zealand":
    - "Australia"
    - "Christmas Island"
    - "Cocos (Keeling) Islands"
    - "Heard Island and McDonald Islands"
    - "New Zealand"
    - "Norfolk Island"
    
  # Melanesia
  "Melanesia":
    - "Fiji"
    - "New Caledonia"
    - "Papua New Guinea"
    - "Solomon Islands"
    - "Vanuatu"
    
  # Micronesia
  "Micronesia":
    - "Guam"
    - "Kiribati"
    - "Marshall Islands"
    - "Micronesia (Federated States of)"
    - "Micronesia (Fed. States of)"
    - "Nauru"
    - "Northern Mariana Islands"
    - "Palau"
    
  # Polynesia
  "Polynesia":
    - "American Samoa"
    - "Cook Islands"
    - "French Polynesia"
    - "Niue"
    - "Pitcairn"
    - "Samoa"
    - "Tokelau"
    - "Tonga"
    - "Tuvalu"
    - "Wallis and Futuna Islands"

# Region to Continent mapping
region_to_continent:
  "Africa":
    - "Eastern Africa"
    - "Middle Africa"
    - "Northern Africa"
    - "Southern Africa"
    - "Western Africa"
    
  "Asia":
    - "Central Asia"
    - "Eastern Asia"
    - "South-eastern Asia" 
    - "Southern Asia"
    - "Western Asia"
    
  "Europe":
    - "Eastern Europe"
    - "Northern Europe"
    - "Southern Europe"
    - "Western Europe"
    
  "North America":
    - "Caribbean"
    - "Central America"
    - "Northern America"
    
  "South America":
    - "South America"
    
  "Oceania":
    - "Australia and New Zealand"
    - "Melanesia"
    - "Micronesia"
    - "Polynesia"

# Metadata
metadata:
  version: "1.0"
  last_updated: "2025-06-09"
  description: "Geographical hierarchies for regional GRI analysis"
  source: "United Nations geographical regions (M49 standard)"
  notes: |
    - Based on UN Statistical Division M49 standard
    - Allows aggregation from country -> region -> continent
    - Supports flexible geographical analysis granularity